<project xmlns="http://maven.apache.org/POM/4.0.0">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>sourcepath</groupId>
    <artifactId>parent</artifactId>
    <version>1.0-SNAPSHOT</version>
  </parent>
  <artifactId>A</artifactId>
  <dependencies>
    <dependency>
      <groupId>sourcepath</groupId>
      <artifactId>B</artifactId>
      <version>${project.version}</version>
      <exclusions>
        <exclusion>
          <groupId>sourcepath</groupId>
          <artifactId>D</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>sourcepath</groupId>
      <artifactId>D</artifactId>
      <version>${project.version}</version>
      <scope>test</scope>
    </dependency>
  </dependencies>
</project>
