# content of service-account-credentials.json, used to access to Google Cloud Platform
gcp_credentials: ENCRYPTED[0f521f37b53602cd374f0da202d56b0160a00e7fc7f11a7d2397263b60b972132816e26fb68954617a93770c338fb580]

#
# ENV VARIABLES
#
env:
  ### Shared variables
  ARTIFACTORY_URL: VAULT[development/kv/data/repox data.url]
  ARTIFACTORY_PRIVATE_USERNAME: vault-${CIRRUS_REPO_OWNER}-${CIRRUS_REPO_NAME}-private-reader
  ARTIFACTORY_PRIVATE_PASSWORD: VAULT[development/artifactory/token/SonarSource-sonar-scanner-maven-private-reader access_token]
  ARTIFACTORY_ACCESS_TOKEN: VAULT[development/artifactory/token/SonarSource-sonar-scanner-maven-private-reader access_token]
  ARTIFACTORY_DEPLOY_USERNAME: vault-${CIRRUS_REPO_OWNER}-${CIRRUS_REPO_NAME}-qa-deployer
  ARTIFACTORY_DEPLOY_PASSWORD: VAULT[development/artifactory/token/SonarSource-sonar-scanner-maven-qa-deployer access_token]
  ARTIFACTORY_DEPLOY_REPO: sonarsource-public-qa

  GCF_ACCESS_TOKEN: VAULT[development/kv/data/promote data.token]
  PROMOTE_URL: VAULT[development/kv/data/promote data.url]

  GITHUB_TOKEN: VAULT[development/github/token/SonarSource-sonar-scanner-maven-ro token]

  BURGR_URL: VAULT[development/kv/data/burgr data.url]
  BURGR_USERNAME: VAULT[development/kv/data/burgr data.cirrus_username]
  BURGR_PASSWORD: VAULT[development/kv/data/burgr data.cirrus_password]

  ### Project variables
  DEPLOY_PULL_REQUEST: true
  ARTIFACTS: org.sonarsource.scanner.maven:sonar-maven-plugin:jar

#
# RE-USABLE CONFIGS
#
container_definition: &CONTAINER_DEFINITION
  image: us.gcr.io/sonarqube-team/base:j11-m3-latest
  cluster_name: cirrus-ci-cluster
  zone: us-central1-a
  namespace: default

container_definition_17: &CONTAINER_DEFINITION_17
  image: us.gcr.io/sonarqube-team/base:j17-m3.8.2-latest
  cluster_name: cirrus-ci-cluster
  zone: us-central1-a
  namespace: default

only_sonarsource_qa: &ONLY_SONARSOURCE_QA
  only_if: $CIRRUS_USER_COLLABORATOR == 'true' && ($CIRRUS_PR != "" || $CIRRUS_BRANCH == "master" || $CIRRUS_BRANCH =~ "branch-.*" || $CIRRUS_BRANCH =~ "dogfood-on-.*")

#
# TASKS
#
build_task:
  gke_container:
    <<: *CONTAINER_DEFINITION
    cpu: 1
    memory: 2G
  env:
    SONAR_TOKEN: VAULT[development/kv/data/next data.token]
    SONAR_HOST_URL: https://next.sonarqube.com/sonarqube
    SIGN_KEY: VAULT[development/kv/data/sign data.key]
    PGP_PASSPHRASE: VAULT[development/kv/data/sign data.passphrase]
  maven_cache:
    folder: ${CIRRUS_WORKING_DIR}/.m2/repository
  script:
    - source cirrus-env BUILD
    - regular_mvn_build_deploy_analyze
  cleanup_before_cache_script:
    - cleanup_maven_repository

qa_task:
  depends_on:
    - build
  <<: *ONLY_SONARSOURCE_QA
  gke_container:
    <<: *CONTAINER_DEFINITION
    cpu: 2
    memory: 4G
  env:
    matrix:
      - SQ_VERSION: LATEST_RELEASE[8.9]
        MAVEN_VERSION: 3.6.1
      - SQ_VERSION: LATEST_RELEASE[8.9]
        MAVEN_VERSION: 3.5.2
      - SQ_VERSION: LATEST_RELEASE[8.9]
        MAVEN_VERSION: 3.3.9
      - SQ_VERSION: LATEST_RELEASE[8.9]
        MAVEN_VERSION: 3.2.5
      - SQ_VERSION: LATEST_RELEASE[8.9]
        MAVEN_VERSION: 3.1.1
      - SQ_VERSION: LATEST_RELEASE[8.9]
        MAVEN_VERSION: 3.0.5
      - SQ_VERSION: DEV
        MAVEN_VERSION: 3.6.1
  maven_cache:
    folder: ${CIRRUS_WORKING_DIR}/.m2/repository
  qa_script:
    - ./cirrus/cirrus-qa.sh
  cleanup_before_cache_script:
    - cleanup_maven_repository

qa_j17_task:
  depends_on:
    - build
  <<: *ONLY_SONARSOURCE_QA
  gke_container:
    <<: *CONTAINER_DEFINITION_17
    cpu: 2
    memory: 4G
  env:
    SQ_VERSION: DEV
    MAVEN_VERSION: 3.8.5
  maven_cache:
    folder: ${CIRRUS_WORKING_DIR}/.m2/repository
  qa_script:
    - ./cirrus/cirrus-qa.sh
  cleanup_before_cache_script:
    - cleanup_maven_repository

promote_task:
  depends_on:
    - qa
  <<: *ONLY_SONARSOURCE_QA
  gke_container:
    <<: *CONTAINER_DEFINITION
    cpu: 0.5
    memory: 500M
  env:
    GITHUB_TOKEN: VAULT[development/github/token/SonarSource-sonar-scanner-maven-promotion token]
  maven_cache:
    folder: $CIRRUS_WORKING_DIR/.m2/repository
  script:
    - cirrus_promote_maven
  cleanup_before_cache_script:
    - cleanup_maven_repository
