name: Unified Dogfooding scans
on:
  schedule:
    - cron: '0 4 * * *' # Run the workflow every day at 04:00 UTC
  workflow_dispatch:

jobs:
  unified-platform-dogfooding:
    runs-on: github-ubuntu-latest-s
    name: Unified Platform Dogfooding
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: jdx/mise-action@1648a7812b9aeae629881980618f079932869151 # v4.0.1
        with:
          version: 2025.7.12
      - uses: SonarSource/ci-github-actions/build-maven@v1
        with:
          run-shadow-scans: true
          artifactory-reader-role: private-reader
          artifactory-deployer-role: qa-deployer
      - name: Run IRIS Analysis
        uses: SonarSource/unified-dogfooding-actions/run-iris@v1
        with:
          primary_project_key: org.sonarsource.scanner.maven:sonar-scanner-maven
          primary_platform: "Next"
          shadow1_project_key: org.sonarsource.scanner.maven:sonar-scanner-maven
          shadow1_platform: "SQC-EU"
          shadow2_project_key: org.sonarsource.scanner.maven:sonar-scanner-maven
          shadow2_platform: "SQC-US"
